awe:
  version: 20
  rendering:
    interval: 1
    talk-interval: 10
    talk-cooldown: 5
    queue-max-size-hard: 10000000
    queue-max-size-soft: 5000000
  memory:
    minimumHard: 400000
    minimumSoft: 600000
    gcTimeout: 10000
  dispatcher:
    max-jobs: 2000
    max-idle-runs: 200
    max-time: 20
  forceFlushBlocks: 10000
  checkVersion: true
  physicsFreez: true
  strings: english.yml
  debug: false
  blocksHub:
    log:
      isEnabled: true
      isDcEnabled: false
    access:
      isEnabled: false
      isDcEnabled: false
      allowNull: false
      allowUnknown: true
      allowConsole: true
      allowOffline: false
  undo:
    memoryLowMain: cancel
    memoryLow: wait
    memoryLowStorage: wait
    storeOnDisk: true
    keepSessionOnLogoutFor: 0
    keepUndoFileFor: 0
    undoFileCleanupInterval: 30
  directChunk:
    autoRelight: true
    newSectionLightLevel: 0
    blockLightLevel: -1
  permissions:
    opHasAll: true
    disableQueueBypass: true
  permissionGroups:
    default:
      isDefault: true
      maxJobs: 1
      cleanOnLogout: true
      defaultMode: true
      disableUndo: false
      renderer:
        blocks: 10000
        time: 75
      queue:
        limit-hard: 500000
        limit-soft: 250000
      messages:
        progress-bar: true
        progress-bar-min: 100
        progress-chat: true
        talkative: true
      worldedit:
        historySize: 15
        maxBlockChanged: -1
        disallowedBlocks:
        - 6
        - 7
        - 14
        - 15
        - 16
        - 26
        - 27
        - 28
        - 29
        - 39
        - 31
        - 32
        - 33
        - 34
        - 36
        - 37
        - 38
        - 39
        - 40
        - 46
        - 50
        - 51
        - 56
        - 59
        - 69
        - 73
        - 74
        - 75
        - 76
        - 77
        - 81
        - 83
        disallowedBlocksUsage:
          patterns: true
          blockSet: false
  disabledOperations: {}
  overrides:
    disableForWeApi: false
    disableForConsole: false
    disableForUnknown: false
